### PR TITLE
Initial project deployment

### PR DESCRIPTION
**Pull request by ykh9871**
backend and frontend Initial project deployment

### CODE REVIEW

**Comment by ykh9871** [comment]
초기 백과 프론트의 프로젝트 구성을 올렸습니다

**Review by Atopiano — APPROVED** [review]
so good

**Review by jewoodev — COMMENTED** [review]
All conservation is resloved on Slack.
image
image
image
image

**Review by jewoodev — APPROVED** [review]
Ready to be merged.

**Comment by jewoodev** [comment]
'.idea' can make confliction because all team member own personal project folder.

**Comment by jewoodev** [comment]
Reason of '.idea' removed is that all team member can own personal project folder so it will make confliction.

**Pull request merged**
